# Generated by Django 4.2.1 on 2023-05-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_parent_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Nomi')),
            ],
            options={
                'verbose_name_plural': 'Xil(xususiyat)',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoriya', 'verbose_name_plural': 'Categoriyalar'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Holati Aktiv'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_count',
            field=models.IntegerField(default=0, verbose_name='Sotilganlar soni'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name="Ko'rganlar soni"),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=264, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Ota kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=255, verbose_name="O'lchov birligi")),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Narxi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati Aktiv')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name_plural': 'Mahsulot Narxlari',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='product/media', verbose_name='Video/Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati Aktiv')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_media', to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name_plural': 'Mahsulot Video/rasmlari',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.character', verbose_name='Mahsulot xususiyati')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_character', to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name_plural': 'Mahsulot xususiyati',
            },
        ),
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Haqida')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.country', verbose_name='Ishlab chiqligan')),
            ],
            options={
                'verbose_name': 'Ishlab Chiqqan Zavod',
                'verbose_name_plural': 'Ishlab Chiqqan Zavodlar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.country', verbose_name='Ishlab chiqligan davlat'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufactory_re', to='product.manufactory', verbose_name='Ishlab chiqqan Korxona'),
        ),
    ]
