# Generated by Django 4.2.1 on 2023-05-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_income_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_id',
            field=models.CharField(default='#e006718c', max_length=255, verbose_name='Mahsulot ID raqami'),
        ),
    ]
