# Generated by Django 4.2.1 on 2023-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_alter_income_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_id',
            field=models.CharField(default='#54a1348b', max_length=255, unique=True, verbose_name='Mahsulot ID raqami'),
        ),
    ]
