# Generated by Django 4.2.1 on 2023-05-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_alter_income_income_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_id',
        ),
        migrations.AddField(
            model_name='income',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AddField(
            model_name='incomeitem',
            name='self_price',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True, verbose_name='Mahsulot kelish narxi'),
        ),
    ]
